// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zngiygsbonrgomkrsany.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZ2l5Z3Nib25yZ29ta3JzYW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTk5OTIsImV4cCI6MjA2NDk5NTk5Mn0.SrX-H6s4mFKrV5ZQaeMRujBRHjLbYqicpW4y5-B_Uhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);