name: Automatic Content Update

on:
  schedule:
    # This runs the workflow every hour.
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Gets a copy of your code for the bot to work with.
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: This is a test to show the automation works.
      # It creates a file named "last-update.txt" and puts the current date inside it.
      - name: Update timestamp file
        run: echo "Last updated: $(date)" > last-update.txt

      # Step 3: Saves the changes back to your repository.
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "Automated News Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automated content update"
          git push
